# See config.example.yml for documentation.
object: orig/GGVE78/sys/main.dol
hash: f772db7f38b9b55e27169822ed17184fa2dc2574
symbols: config/GGVE78/symbols.txt
splits: config/GGVE78/splits.txt
symbols_known: true
fill_gaps: false
ldscript_template: config/GGVE78/ldscript.tpl
